#!/usr/bin/env bash

############################################################
# Constants                                                #
############################################################

# Define constants
declare -r CACHE_DIRECTORY="$HOME/.gitignore-cache"
declare -r REPOSITORY_URL="https://github.com/github/gitignore.git"
declare -r CUSTOM_RULES_FILE=".custom.gitignore"
declare -r VERSION="1.0.0"

############################################################
# Commands                                                 #
############################################################

# Generates a combined gitignore file from the specified templates
# @param $@ The list of the gitiginore templates to use
function generate() {
    create_or_update_cache

    echo "# Generated using 'gitignore generate $@'"
    echo ""

    if [ -f "$CUSTOM_RULES_FILE" ]
    then
        echo "####### START OF $CUSTOM_RULES_FILE #######"
        echo ""
        cat $CUSTOM_RULES_FILE
        # Ensure there is a line break at the end of each file
        echo ""
        echo "####### END OF $CUSTOM_RULES_FILE #######"
        echo ""
    fi

    for file in "$@"
    do
        echo "####### START OF $file.gitignore #######"
        echo ""
        cat "$CACHE_DIRECTORY/$file.gitignore"
        # Ensure there is a line break at the end of each file
        echo ""
        echo "####### END OF $file.gitignore #######"
        echo ""
    done
}

# Batch search all available gitignore files for the specified queries
# @param $@ The search queries
function search() {
    create_or_update_cache

    for query in "$@"
    do
        list | grep -i $query
    done    
}

# Lists all available gitignore templates
function list() {
    create_or_update_cache
    find $CACHE_DIRECTORY -name "*.gitignore" | sed "s|$CACHE_DIRECTORY/||" | sed "s|.gitignore||" | sort
}

# Display help information
function help() {
    echo "gitignore $VERSION"
    echo "Effortlessly generate .gitignore files from the command line using the GitHub templates."
    echo ""
    echo "Usage: gitignore [command] [arguments]"
    echo "Commands:"
    echo "  generate [template] [template] ... - Generates a combined gitignore file from the specified templates"
    echo "  search [query] [query] ...         - Batch search all available gitignore files for the specified queries"
    echo "  list                               - Lists all available gitignore templates"
    echo "  help                               - Display help information"
    echo "More information: https://github.com/bilaalrashid/gitignore"
}

############################################################
# Utility functions                                        #
############################################################

# Handles creating or updating the cached gitignore files
function create_or_update_cache() {
    if does_cache_exist
    then 
        update_cache
    else 
        create_gitignore_cache
    fi
}

# Checks if the cached gitignore files exist
function does_cache_exist() {
    [ -d "$CACHE_DIRECTORY" ]
}

# Updates the cached gitignore files
function update_cache() {
    git -C $CACHE_DIRECTORY pull > /dev/null
}

# Creates a cache of the gitignore files
function create_gitignore_cache() {
    git clone $REPOSITORY_URL $CACHE_DIRECTORY > /dev/null
}

############################################################
# Main                                                     #
############################################################

# Required as this is invoked as a script rather than sourced
# This MUST be the first operation other than the function definitions
[[ $_ != $0 ]]

utility_commands=("create_or_update_cache" "does_cache_exist" "update_cache" "create_gitignore_cache")

# Check a valid function was specified
if declare -f "$1" >/dev/null 2>&1 && [[ ! " ${utility_commands[*]} " =~ " ${1} " ]]
then
  # Invoke the specified function, passing arguments through
  "$@" # Same as "$1" "$2" "$3" ... for full argument list
else
  echo "Invalid command" >&2
  echo ""
  help
  exit 1
fi
